<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">
  <PropertyGroup>
    <Description>Do more conf in app.config</Description>
    <PackageTags>.NET App Config;App Config</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domore.Conf\Domore.Conf.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <Reference Include="System.Configuration" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' != 'net'">
    <PackageReference Include="System.Configuration.ConfigurationManager" />
  </ItemGroup>
</Project>