<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Do more conf in app.config</Description>
    <PackageTags>app-config;appconfig;app.config;ConfigurationManager;configuration;conf;domore</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domore.Conf\Domore.Conf.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <Reference Include="System.Configuration" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' != 'net'">
    <PackageReference Include="System.Configuration.ConfigurationManager" />
  </ItemGroup>
</Project>