<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0-windows;net10.0-windows</TargetFrameworks>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\source\Domore.Async.TextReading.Windows\Domore.Async.TextReading.Windows.csproj" />
  </ItemGroup>
</Project>
