<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Do more conf</Description>
    <PackageTags>conf;config;configuration;conf-files;config-files;configuration-files;settings;dotnet;domore</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <Import Project="..\..\shared\Domore.Sharing\Domore.Sharing.projitems" Label="Shared" />
</Project>