<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\success_unicode_1" />
    <EmbeddedResource Include="Resources\success_unicode_2" />
    <EmbeddedResource Include="Resources\success_unicode_3" />
    <EmbeddedResource Include="Resources\success_unicode_4" />
    <EmbeddedResource Include="Resources\success_unicode_5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\source\Domore.Async.TextReading\Domore.Async.TextReading.csproj" />
  </ItemGroup>
</Project>
